# Generated by Django 5.2.4 on 2025-08-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_expert_availability_remove_expert_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='session',
        ),
        migrations.DeleteModel(
            name='ChatSession',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
